"""making changes

Revision ID: b9e104870a28
Revises: 5045ed09eb9e
Create Date: 2022-02-22 23:10:07.607406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e104870a28'
down_revision = '5045ed09eb9e'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users_sign_in', ['id', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_sign_in', type_='unique')
    # ### end Alembic commands ###
