# Generated by Django 3.2 on 2022-05-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='creation_year',
            field=models.TextField(blank=True, verbose_name='creation year'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='kinopoisk_id',
            field=models.TextField(blank=True, verbose_name='kinopoisk_id'),
        ),
        migrations.AlterField(
            model_name='person',
            name='kinopoisk_id',
            field=models.TextField(blank=True, verbose_name='kinopoisk_id'),
        ),
        migrations.AddConstraint(
            model_name='filmwork',
            constraint=models.UniqueConstraint(fields=('kinopoisk_id',), name='film_work_kinopoisk_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('kinopoisk_id',), name='person_kinopoisk_id_uniq'),
        ),
    ]
