# Generated by Django 3.2 on 2022-05-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220510_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='creation_year',
            field=models.CharField(blank=True, max_length=20, verbose_name='creation year'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='kinopoisk_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='kinopoisk_id'),
        ),
    ]
