# Generated by Django 3.2 on 2022-05-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20220510_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='kinopoisk_id',
            field=models.TextField(blank=True, null=True, verbose_name='kinopoisk_id'),
        ),
    ]
