version: '3.9'

services:
  es:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
  movies-api:
    container_name: movies_search
    image: movies_search:v3.0
    build:
      context: .
      dockerfile: movies_api/docker/Dockerfile
    env_file:
      - movies_api/envs/.movies_api.env
    depends_on:
      - es
      - redis
  redis:
    container_name: redis
    image: redis:6.2.6-alpine
    restart: always
    volumes:
      - redis_data:/data
  test-movies-api:
    container_name: test_movies_api
    image: test_movies_api:v1.0
    build:
      context: .
      dockerfile: movies_api/tests/docker/Dockerfile
    env_file:
      - movies_api/envs/.movies_api.env
    depends_on:
      - es
      - redis
volumes:
  redis_data:
  elastic_data:
