# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, has_roles: bool=None, message: str=None, status: str=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param has_roles: The has_roles of this InlineResponse2001.  # noqa: E501
        :type has_roles: bool
        :param message: The message of this InlineResponse2001.  # noqa: E501
        :type message: str
        :param status: The status of this InlineResponse2001.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'has_roles': bool,
            'message': str,
            'status': str
        }

        self.attribute_map = {
            'has_roles': 'has_roles',
            'message': 'message',
            'status': 'status'
        }
        self._has_roles = has_roles
        self._message = message
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def has_roles(self) -> bool:
        """Gets the has_roles of this InlineResponse2001.


        :return: The has_roles of this InlineResponse2001.
        :rtype: bool
        """
        return self._has_roles

    @has_roles.setter
    def has_roles(self, has_roles: bool):
        """Sets the has_roles of this InlineResponse2001.


        :param has_roles: The has_roles of this InlineResponse2001.
        :type has_roles: bool
        """

        self._has_roles = has_roles

    @property
    def message(self) -> str:
        """Gets the message of this InlineResponse2001.


        :return: The message of this InlineResponse2001.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this InlineResponse2001.


        :param message: The message of this InlineResponse2001.
        :type message: str
        """

        self._message = message

    @property
    def status(self) -> str:
        """Gets the status of this InlineResponse2001.


        :return: The status of this InlineResponse2001.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this InlineResponse2001.


        :param status: The status of this InlineResponse2001.
        :type status: str
        """

        self._status = status
