# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Passwords(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, new_password: str=None, old_password: str=None):  # noqa: E501
        """Passwords - a model defined in Swagger

        :param new_password: The new_password of this Passwords.  # noqa: E501
        :type new_password: str
        :param old_password: The old_password of this Passwords.  # noqa: E501
        :type old_password: str
        """
        self.swagger_types = {
            'new_password': str,
            'old_password': str
        }

        self.attribute_map = {
            'new_password': 'new_password',
            'old_password': 'old_password'
        }
        self._new_password = new_password
        self._old_password = old_password

    @classmethod
    def from_dict(cls, dikt) -> 'Passwords':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Passwords of this Passwords.  # noqa: E501
        :rtype: Passwords
        """
        return util.deserialize_model(dikt, cls)

    @property
    def new_password(self) -> str:
        """Gets the new_password of this Passwords.


        :return: The new_password of this Passwords.
        :rtype: str
        """
        return self._new_password

    @new_password.setter
    def new_password(self, new_password: str):
        """Sets the new_password of this Passwords.


        :param new_password: The new_password of this Passwords.
        :type new_password: str
        """
        if new_password is None:
            raise ValueError("Invalid value for `new_password`, must not be `None`")  # noqa: E501

        self._new_password = new_password

    @property
    def old_password(self) -> str:
        """Gets the old_password of this Passwords.


        :return: The old_password of this Passwords.
        :rtype: str
        """
        return self._old_password

    @old_password.setter
    def old_password(self, old_password: str):
        """Sets the old_password of this Passwords.


        :param old_password: The old_password of this Passwords.
        :type old_password: str
        """
        if old_password is None:
            raise ValueError("Invalid value for `old_password`, must not be `None`")  # noqa: E501

        self._old_password = old_password
