# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Permission(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: str=None, description: str=None, id: str=None):  # noqa: E501
        """Permission - a model defined in Swagger

        :param code: The code of this Permission.  # noqa: E501
        :type code: str
        :param description: The description of this Permission.  # noqa: E501
        :type description: str
        :param id: The id of this Permission.  # noqa: E501
        :type id: str
        """
        self.swagger_types = {
            'code': str,
            'description': str,
            'id': str
        }

        self.attribute_map = {
            'code': 'code',
            'description': 'description',
            'id': 'id'
        }
        self._code = code
        self._description = description
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'Permission':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Permission of this Permission.  # noqa: E501
        :rtype: Permission
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this Permission.


        :return: The code of this Permission.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this Permission.


        :param code: The code of this Permission.
        :type code: str
        """

        self._code = code

    @property
    def description(self) -> str:
        """Gets the description of this Permission.


        :return: The description of this Permission.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Permission.


        :param description: The description of this Permission.
        :type description: str
        """

        self._description = description

    @property
    def id(self) -> str:
        """Gets the id of this Permission.


        :return: The id of this Permission.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Permission.


        :param id: The id of this Permission.
        :type id: str
        """

        self._id = id
