# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Response500(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, message: str=None, sentry: str=None, status: str=None):  # noqa: E501
        """Response500 - a model defined in Swagger

        :param message: The message of this Response500.  # noqa: E501
        :type message: str
        :param sentry: The sentry of this Response500.  # noqa: E501
        :type sentry: str
        :param status: The status of this Response500.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'message': str,
            'sentry': str,
            'status': str
        }

        self.attribute_map = {
            'message': 'message',
            'sentry': 'sentry',
            'status': 'status'
        }
        self._message = message
        self._sentry = sentry
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Response500':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Response500 of this Response500.  # noqa: E501
        :rtype: Response500
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this Response500.


        :return: The message of this Response500.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this Response500.


        :param message: The message of this Response500.
        :type message: str
        """

        self._message = message

    @property
    def sentry(self) -> str:
        """Gets the sentry of this Response500.


        :return: The sentry of this Response500.
        :rtype: str
        """
        return self._sentry

    @sentry.setter
    def sentry(self, sentry: str):
        """Sets the sentry of this Response500.


        :param sentry: The sentry of this Response500.
        :type sentry: str
        """

        self._sentry = sentry

    @property
    def status(self) -> str:
        """Gets the status of this Response500.


        :return: The status of this Response500.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Response500.


        :param status: The status of this Response500.
        :type status: str
        """

        self._status = status
