# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserDevice(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, created_at: str=None, ip: str=None, user_agent: str=None):  # noqa: E501
        """UserDevice - a model defined in Swagger

        :param created_at: The created_at of this UserDevice.  # noqa: E501
        :type created_at: str
        :param ip: The ip of this UserDevice.  # noqa: E501
        :type ip: str
        :param user_agent: The user_agent of this UserDevice.  # noqa: E501
        :type user_agent: str
        """
        self.swagger_types = {
            'created_at': str,
            'ip': str,
            'user_agent': str
        }

        self.attribute_map = {
            'created_at': 'created_at',
            'ip': 'ip',
            'user_agent': 'user_agent'
        }
        self._created_at = created_at
        self._ip = ip
        self._user_agent = user_agent

    @classmethod
    def from_dict(cls, dikt) -> 'UserDevice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserDevice of this UserDevice.  # noqa: E501
        :rtype: UserDevice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created_at(self) -> str:
        """Gets the created_at of this UserDevice.


        :return: The created_at of this UserDevice.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: str):
        """Sets the created_at of this UserDevice.


        :param created_at: The created_at of this UserDevice.
        :type created_at: str
        """

        self._created_at = created_at

    @property
    def ip(self) -> str:
        """Gets the ip of this UserDevice.


        :return: The ip of this UserDevice.
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip: str):
        """Sets the ip of this UserDevice.


        :param ip: The ip of this UserDevice.
        :type ip: str
        """

        self._ip = ip

    @property
    def user_agent(self) -> str:
        """Gets the user_agent of this UserDevice.


        :return: The user_agent of this UserDevice.
        :rtype: str
        """
        return self._user_agent

    @user_agent.setter
    def user_agent(self, user_agent: str):
        """Sets the user_agent of this UserDevice.


        :param user_agent: The user_agent of this UserDevice.
        :type user_agent: str
        """

        self._user_agent = user_agent
