# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user_device import UserDevice  # noqa: F401,E501
from swagger_server import util


class UserLogin(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, device: UserDevice=None, login_date: str=None):  # noqa: E501
        """UserLogin - a model defined in Swagger

        :param device: The device of this UserLogin.  # noqa: E501
        :type device: UserDevice
        :param login_date: The login_date of this UserLogin.  # noqa: E501
        :type login_date: str
        """
        self.swagger_types = {
            'device': UserDevice,
            'login_date': str
        }

        self.attribute_map = {
            'device': 'device',
            'login_date': 'login_date'
        }
        self._device = device
        self._login_date = login_date

    @classmethod
    def from_dict(cls, dikt) -> 'UserLogin':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserLogin of this UserLogin.  # noqa: E501
        :rtype: UserLogin
        """
        return util.deserialize_model(dikt, cls)

    @property
    def device(self) -> UserDevice:
        """Gets the device of this UserLogin.


        :return: The device of this UserLogin.
        :rtype: UserDevice
        """
        return self._device

    @device.setter
    def device(self, device: UserDevice):
        """Sets the device of this UserLogin.


        :param device: The device of this UserLogin.
        :type device: UserDevice
        """

        self._device = device

    @property
    def login_date(self) -> str:
        """Gets the login_date of this UserLogin.


        :return: The login_date of this UserLogin.
        :rtype: str
        """
        return self._login_date

    @login_date.setter
    def login_date(self, login_date: str):
        """Sets the login_date of this UserLogin.


        :param login_date: The login_date of this UserLogin.
        :type login_date: str
        """

        self._login_date = login_date
